packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  # ESLint & Prettier
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.8
  prettier: ^3.6.2
  typescript-eslint: ^8.44.1

  # TypeScript
  typescript: ^5.9.2
  tsx: ^4.20.6

  # Tailwind
  tailwindcss: 4.1.11
  tailwindcss-animate: ^1.0.7
  tailwind-merge: 3.3.1

  # React
  react: ^19.1.1
  react-dom: ^19.1.1
  next-themes: 0.4.6
  sonner: 2.0.6
  class-variance-authority: 0.7.1

ignoredBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - oxc-resolver
  - sharp

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: ">=0.25.0"
